#DBT CLOUD SETTINGS
DBT:
  DBT_PAT : '1086a0bfb6a076f8122139167ca1ea2547203da0' #string: dbt Cloud PAT token
  DBT_CLOUD_API : 'https://cloud.getdbt.com/api/v2/accounts/' #string: dbt Cloud API endpoint
  DBT_METADATA_API : 'https://metadata.cloud.getdbt.com/graphql' #string: dbt Cloud Metadata API endpoint
  DBT_META_CERTIFICATION_FLAG : 'TableauCertified' #string: boolean dbt meta config used to indicate whether tableau table should be certified. see https://docs.getdbt.com/reference/resource-configs/meta
  DBT_PROJECT_FILTER : ["jaffle_shop_metrics", "football_transfers_demo"] #list: list of dbt projects to sync. Leave empty list to sync all dbt projects

#TABLEAU SETTINGS
TABLEAU:
  TABLEAU_TOKEN_NAME : 'dbt' #string: tableau PAT token name
  TABLEAU_TOKEN : 'VyJHyN7NQFKFHwQMX1LjfQ==:NS7kXssry1W2CZGfyatyP1nGVfGRxtin' #string: tableau PAT token
  TABLEAU_SITE : 'tableaujunkietest' #string: tableau site name
  TABLEAU_SERVER : 'https://prod-uk-a.online.tableau.com' #string: tableau server or cloud url
  DATABASE_TYPE_FILTER : 'snowflake' #string: database type to sync with dbt cloud
  DATABASE_NAME_FILTER : ["DBT", "ANALYTICS"] #list: list of tableau database names to sync with dbt cloud. Leave empty list to sync all databases
  CERTIFICATION_NOTE : 'certified by the meta config in dbt Cloud' #string: note to add to tableau certified tables
  DQ_WARNING_IS_SEVERE : True #boolean: flag whether to use severe tableau data quality warnings where latest dbt run not successful